"use client";

import { useState, useEffect } from "react";
import { SignedIn, SignedOut, SignInButton, UserButton } from "@clerk/nextjs";

const TECH_STACKS: Record<string, string[]> = {
  "Node.js (TypeScript)": ["Express", "NestJS", "Next.js (App Router)", "Fastify", "Hono", "Remix"],
  "Python": ["FastAPI", "Django", "Flask", "Tornado", "Litestar"],
  "Java": ["Spring Boot", "Jakarta EE", "Quarkus", "Micronaut"],
  "Go (Golang)": ["Gin", "Echo", "Fiber", "Chi", "Standard Lib"],
  "C# (.NET)": [".NET Web API", "Blazor Server", "Blazor Wasm", "ASP.NET MVC"],
  "Rust": ["Actix-web", "Axum", "Rocket", "Tokio"],
  "PHP": ["Laravel", "Symfony", "CodeIgniter", "Slim"],
  "Ruby": ["Ruby on Rails", "Sinatra", "Hanami"]
};

const DATABASES = [
  "PostgreSQL (Prisma)", "PostgreSQL (TypeORM)", "MongoDB (Mongoose)", 
  "MySQL", "SQLite", "Redis", "Supabase", "Firebase", "None"
];

const AUTH_OPTIONS = ["None", "JWT (Custom)", "NextAuth.js", "Firebase Auth", "Auth0", "Clerk"];
const TESTING_TOOLS = ["None", "Jest", "Vitest", "PyTest", "JUnit", "Cypress"];

export default function Home() {
  const [language, setLanguage] = useState("Node.js (TypeScript)");
  const [framework, setFramework] = useState(TECH_STACKS["Node.js (TypeScript)"][0]);
  const [db, setDb] = useState("PostgreSQL (Prisma)");
  
  const [showAdvanced, setShowAdvanced] = useState(false);
  const [auth, setAuth] = useState("None");
  const [testing, setTesting] = useState("None");
  const [docker, setDocker] = useState(false);
  const [ciCd, setCiCd] = useState(false);

  const [loading, setLoading] = useState(false);
  const [status, setStatus] = useState("");

  useEffect(() => {
    setFramework(TECH_STACKS[language][0]);
  }, [language]);

  const handleGenerate = async () => {
    setLoading(true);
    setStatus("Architecting your solution...");

    let prompt = `Language: ${language}, Framework: ${framework}, Database: ${db}`;
    if (auth !== "None") prompt += `, Authentication: ${auth}`;
    if (testing !== "None") prompt += `, Testing: ${testing}`;
    if (docker) prompt += `, Include Dockerfile & docker-compose`;
    if (ciCd) prompt += `, Include GitHub Actions CI/CD workflow`;

    try {
      const response = await fetch("/api/generate", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ prompt }),
      });

      const data = await response.json();
      if (!response.ok) throw new Error(data.error);

      if (data.url) {
        setStatus(data.cached ? "Cache HIT! ⚡ Instant Download" : "Generated by AI! 🤖 Downloading...");
        
        const a = document.createElement("a");
        a.href = data.url;
        a.download = `boilerplate-${framework.toLowerCase().replace(/ /g, "-")}.zip`;
        document.body.appendChild(a);
        a.click();
        a.remove();
      }
    } catch (error) {
      console.error(error);
      alert("Something went wrong. Please try again.");
    } finally {
      setLoading(false);
      setTimeout(() => setStatus(""), 4000);
    }
  };

  return (
    <div className="min-h-screen bg-slate-50 text-slate-900 font-sans relative">
      
      {/* Beta Banner */}
      <div className="bg-indigo-600 text-white text-center text-sm font-medium py-2 px-4">
        🚀 Public Beta: All Pro features (Docker, CI/CD) are <span className="font-bold underline">Free</span> for a limited time!
      </div>

      {/* Navbar */}
      <nav className="w-full flex justify-between items-center p-6 px-8 max-w-7xl mx-auto">
         <div className="text-xl font-bold text-slate-800 flex items-center gap-2">
            <span className="text-2xl">🏗️</span> Code Architect
         </div>
         <div className="flex items-center gap-4">
            {/* Feedback Button */}
            <a 
              href="mailto:your-email@gmail.com?subject=Code Architect Feedback"
              className="hidden md:block text-sm text-slate-500 hover:text-blue-600 transition"
            >
              Give Feedback
            </a>

            <SignedOut>
              <SignInButton mode="modal">
                <button className="bg-white text-blue-600 px-5 py-2 rounded-full font-bold shadow-sm hover:shadow-md transition-all border border-blue-100">
                  Sign In
                </button>
              </SignInButton>
            </SignedOut>

            <SignedIn>
              <div className="flex items-center gap-4">
                <a href="/dashboard" className="text-sm font-bold text-slate-600 hover:text-blue-600 transition">
                  History
                </a>
                <UserButton afterSignOutUrl="/" />
              </div>
            </SignedIn>
         </div>
      </nav>

      <div className="py-8 px-4 flex flex-col items-center">
        <div className="text-center mb-10 space-y-3">
          <h1 className="text-5xl font-extrabold text-slate-800 tracking-tight">
            Generate Production-Ready <br/> <span className="text-blue-600">Backend Boilerplates</span>
          </h1>
          <p className="text-lg text-slate-600 max-w-2xl mx-auto leading-relaxed">
            Stop wasting time on config. Get a complete project structure with
            <span className="font-semibold text-slate-800"> Docker, Auth, and CI/CD </span>
            in seconds.
          </p>
        </div>

        <div className="w-full max-w-2xl bg-white rounded-2xl shadow-2xl border border-slate-200 overflow-hidden relative">
          {/* Terminal Header */}
          <div className="bg-slate-900 p-4 flex gap-2 items-center">
            <div className="w-3 h-3 rounded-full bg-red-500"></div>
            <div className="w-3 h-3 rounded-full bg-yellow-500"></div>
            <div className="w-3 h-3 rounded-full bg-green-500"></div>
            <span className="ml-4 text-slate-400 text-sm font-mono opacity-70">~/generate.sh</span>
          </div>

          <div className="p-8 space-y-8">
            {/* Core Selections */}
            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
              <div className="space-y-2">
                <label className="text-xs font-bold text-slate-500 uppercase tracking-wider">Language</label>
                <select 
                  value={language} onChange={(e) => setLanguage(e.target.value)}
                  className="w-full p-3 bg-slate-50 border border-slate-300 rounded-lg focus:ring-2 focus:ring-blue-500 outline-none"
                >
                  {Object.keys(TECH_STACKS).map((lang) => <option key={lang} value={lang}>{lang}</option>)}
                </select>
              </div>
              <div className="space-y-2">
                <label className="text-xs font-bold text-slate-500 uppercase tracking-wider">Framework</label>
                <select 
                  value={framework} onChange={(e) => setFramework(e.target.value)}
                  className="w-full p-3 bg-slate-50 border border-slate-300 rounded-lg focus:ring-2 focus:ring-blue-500 outline-none"
                >
                  {TECH_STACKS[language].map((fm) => <option key={fm} value={fm}>{fm}</option>)}
                </select>
              </div>
              <div className="space-y-2 md:col-span-2">
                <label className="text-xs font-bold text-slate-500 uppercase tracking-wider">Database</label>
                <select 
                  value={db} onChange={(e) => setDb(e.target.value)}
                  className="w-full p-3 bg-slate-50 border border-slate-300 rounded-lg focus:ring-2 focus:ring-blue-500 outline-none"
                >
                  {DATABASES.map((d) => <option key={d} value={d}>{d}</option>)}
                </select>
              </div>
            </div>

            {/* Advanced Settings (Unlocked) */}
            <div className="border-t border-slate-100 pt-4">
              <button 
                onClick={() => setShowAdvanced(!showAdvanced)}
                className="flex items-center text-blue-600 font-semibold hover:text-blue-800 transition-colors text-sm"
              >
                {showAdvanced ? "🔽 Hide Advanced Settings" : "▶ Show Advanced Settings (Free)"}
              </button>

              {showAdvanced && (
                <div className="mt-6 grid grid-cols-1 md:grid-cols-2 gap-6 bg-blue-50 p-6 rounded-xl animate-in fade-in slide-in-from-top-4 duration-300 border border-blue-100">
                  <div className="space-y-2">
                    <label className="text-xs font-bold text-blue-800 uppercase tracking-wider">Authentication</label>
                    <select value={auth} onChange={(e) => setAuth(e.target.value)} className="w-full p-2 bg-white border border-blue-200 rounded text-sm">
                      {AUTH_OPTIONS.map(o => <option key={o} value={o}>{o}</option>)}
                    </select>
                  </div>
                  <div className="space-y-2">
                    <label className="text-xs font-bold text-blue-800 uppercase tracking-wider">Testing</label>
                    <select value={testing} onChange={(e) => setTesting(e.target.value)} className="w-full p-2 bg-white border border-blue-200 rounded text-sm">
                      {TESTING_TOOLS.map(o => <option key={o} value={o}>{o}</option>)}
                    </select>
                  </div>
                  <div className="flex items-center space-x-3 bg-white p-3 rounded border border-blue-100">
                    <input type="checkbox" id="docker" checked={docker} onChange={(e) => setDocker(e.target.checked)} className="w-5 h-5 text-blue-600 rounded"/>
                    <label htmlFor="docker" className="text-sm font-medium text-slate-700">🐳 Include Docker</label>
                  </div>
                  <div className="flex items-center space-x-3 bg-white p-3 rounded border border-blue-100">
                    <input type="checkbox" id="cicd" checked={ciCd} onChange={(e) => setCiCd(e.target.checked)} className="w-5 h-5 text-blue-600 rounded"/>
                    <label htmlFor="cicd" className="text-sm font-medium text-slate-700">🤖 GitHub Actions</label>
                  </div>
                </div>
              )}
            </div>

            <button
              onClick={handleGenerate}
              disabled={loading}
              className={`w-full py-4 px-6 text-lg font-bold text-white rounded-xl shadow-lg transition-all transform active:scale-[0.98] ${
                loading ? "bg-slate-400 cursor-not-allowed" : "bg-gradient-to-r from-blue-600 to-indigo-600 hover:shadow-blue-500/30"
              }`}
            >
              {loading ? "Architecting Solution..." : "Generate Boilerplate 🚀"}
            </button>

            {status && (
              <div className="text-center p-4 rounded-lg border text-sm font-mono font-medium bg-indigo-50 border-indigo-200 text-indigo-700">
                {`> ${status}`}
              </div>
            )}
          </div>
        </div>
        <div className="mt-10 text-slate-400 text-sm">© 2025 Code Architect</div>
      </div>
    </div>
  );
}